version: "3.9"
services:
  web:
    image: ${IMAGE:-doger-web:latest}
    # or uncomment to build locally instead of pulling
    # build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
    # No volumes; use baked image with collectstatic + whitenoise
    restart: unless-stopped

  # Optional realtime presence bot (requires DISCORD_BOT_TOKEN)
  bot:
    image: ${IMAGE:-doger-web:latest}
    working_dir: /app
    command: sh -c "pip install -q --no-cache-dir discord.py && python bot/main.py"
    env_file:
      - .env
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_PRESENCE_USER_ID=${DISCORD_PRESENCE_USER_ID:-${DISCORD_OWNER_ID}}
      - DISCORD_PRESENCE_FILE=${DISCORD_PRESENCE_FILE:-runtime/presence.json}
      - DISCORD_WIDGET_GUILD_ID=${DISCORD_WIDGET_GUILD_ID}
    volumes:
      - .:/app
    restart: unless-stopped

